name: Learning Progress

on:
  schedule:
    - cron: '13 7 * * *'
    - cron: '28 11 * * *'
    - cron: '42 15 * * *'
    - cron: '07 20 * * *'
    - cron: '51 23 * * *'
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  commit-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set timezone to Europe/Berlin
        run: sudo timedatectl set-timezone Europe/Berlin

      - name: Read picked time
        id: timecheck
        run: |
          PICKED=$(cat picked-time.txt)
          CUR_HOUR=$(date +%H)
          CUR_MIN=$(date +%M)
          CUR_TIME="${CUR_HOUR#0}:${CUR_MIN#0}"
          echo "Picked: $PICKED | Now: $CUR_TIME"

          if [ "$CUR_TIME" = "$PICKED" ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - name: Select random topic
        if: steps.timecheck.outputs.run == 'true'
        id: pick_topic
        run: |
          TOPIC=$(shuf -n 1 topics.txt)
          echo "topic=$TOPIC" >> $GITHUB_OUTPUT

      - name: Update log.txt
        if: steps.timecheck.outputs.run == 'true'
        run: echo "$(date '+%Y-%m-%d') - ${{ steps.pick_topic.outputs.topic }}" >> log.txt

      - name: Commit and push changes
        if: steps.timecheck.outputs.run == 'true'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "ErkanBarann"
          git config user.email "115561897+ErkanBarann@users.noreply.github.com"
          git add log.txt
          git commit -m "Log: $(date '+%Y-%m-%d') - ${{ steps.pick_topic.outputs.topic }}" || echo "No changes"
          git remote set-url origin https://ErkanBarann:${GH_TOKEN}@github.com/ErkanBarann/learning-lab.git
          git push origin main
