name: Learning Progress

on:
  schedule:
    - cron: '0 7 * * *'  # Her gün sabah 07:00'de (UTC) tetiklenir
  workflow_dispatch:

jobs:
  commit-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set timezone to Europe/Berlin
        run: sudo timedatectl set-timezone Europe/Berlin

      - name: Pick random delay between 0 and 900 minutes (15 saat)
        id: delay
        run: |
          MINUTES=2
          echo "Delaying for $MINUTES minutes..."
          echo "sleep_minutes=$MINUTES" >> $GITHUB_OUTPUT

      - name: Sleep for the picked duration
        run: |
          MINUTES=${{ steps.delay.outputs.sleep_minutes }}
          echo "Sleeping for $MINUTES minutes..."
          sleep $((MINUTES * 60))

      - name: Pick random topic from topics.txt
        id: pick_topic
        run: |
          TOPIC=$(shuf -n 1 topics.txt)
          echo "topic=$TOPIC" >> $GITHUB_OUTPUT

      - name: Update log.txt with new topic
        run: |
          echo "$(date '+%Y-%m-%d %H:%M') - ${{ steps.pick_topic.outputs.topic }}" >> log.txt

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "ErkanBarann"
          git config user.email "115561897+ErkanBarann@users.noreply.github.com"
          git add log.txt
          git commit -m "Log: $(date '+%Y-%m-%d %H:%M') - ${{ steps.pick_topic.outputs.topic }}" || echo "No changes to commit"
          git remote set-url origin https://ErkanBarann:${GH_TOKEN}@github.com/ErkanBarann/learning-lab.git
          git push origin main
